package com.tarosie.granularity.client;

import com.tarosie.granularity.Granularity;
import com.tarosie.granularity.content.GranularityBlocks;
import com.tarosie.granularity.core.CompositionLayers;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.client.resources.model.ModelBakery;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.client.event.ModelEvent;
import com.tarosie.granularity.content.GranularityItems;
import com.tarosie.granularity.core.GrainClass;
import java.util.Map;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import org.jetbrains.annotations.Nullable;

/**
 * Swaps the baked model for natural stone with {@link CompositionBakedModel}.
 *
 * <p>The layer models have no blockstate pointing at them, so nothing would bake them; they are
 * requested explicitly through {@link ModelEvent.RegisterAdditional} and collected once baking has
 * produced them. Composing already-baked JSON models is deliberate — hand-baking quads would mean
 * reimplementing UV mapping, face rotation and shading for no gain, and every layer here is an
 * ordinary tinted cube that vanilla bakes correctly on its own.
 *
 * <p>Sprites and models are generated by {@code tools/extract_textures.py} from vanilla's own
 * textures; Phase 3 replaces that script with datagen.
 */
public final class GranularityModels {

    private static final ResourceLocation BASE = model("natural_stone_base");

    /**
     * How many steps the stone-to-deepslate ramp is cut into. Must match {@code DEPTH_BANDS} in
     * {@code tools/extract_textures.py}, which generates one sprite and one model per band.
     */
    private static final int DEPTH_BANDS = 16;

    private static ResourceLocation depthModel(int band) {
        return model("natural_stone_depth_" + band);
    }

    /** Overlay families, in the order they stack. */
    private enum Family {
        ORE("ore", CompositionLayers.MAX_ORE),
        ORE_B("ore_b", CompositionLayers.MAX_ORE),
        PRECIOUS("precious", CompositionLayers.MAX_ORE),
        PRECIOUS_B("precious_b", CompositionLayers.MAX_ORE),
        GEM("gem", CompositionLayers.MAX_ORE),
        GEM_B("gem_b", CompositionLayers.MAX_ORE);

        private final String name;
        private final int steps;

        Family(String name, int steps) {
            this.name = name;
            this.steps = steps;
        }

        ResourceLocation model(int step) {
            return GranularityModels.model("natural_stone_" + name + "_" + step);
        }
    }

    private GranularityModels() {
    }

    /** Wired from the client mod constructor: these are all mod-bus events. */
    public static void register(IEventBus modEventBus) {
        modEventBus.addListener(GranularityModels::registerAdditional);
        modEventBus.addListener(GranularityModels::modifyBakingResult);
        modEventBus.addListener(GranularityModels::registerBlockColours);
        modEventBus.addListener(GranularityModels::registerItemColours);
    }

    private static ResourceLocation model(String path) {
        return ResourceLocation.fromNamespaceAndPath(Granularity.MODID, "block/" + path);
    }


    /**
     * Only natural stone's layers are requested here now.
     *
     * <p>Cobblestone, gravel and the slabs used to be composed the same way — a base model plus nine
     * shape models, stitched into one {@link CompositeBakedModel} at bake time. They are now single
     * models carrying ten elements each, because <b>which</b> overlay they draw never varies; only
     * the tints do, and tints are a colour handler's job, not a model's. Natural stone genuinely
     * does vary its geometry with composition, so it stays.
     *
     * <p>That distinction is what unblocks stairs and walls: geometry living inside one model gets
     * rotated by the blockstate and selected by multipart for free, whereas a model assembled after
     * baking has already missed both.
     */
    public static void registerAdditional(ModelEvent.RegisterAdditional event) {
        event.register(ModelResourceLocation.standalone(BASE));
        for (int band = 0; band < DEPTH_BANDS; band++) {
            event.register(ModelResourceLocation.standalone(depthModel(band)));
        }
        for (Family family : Family.values()) {
            for (int step = 1; step <= family.steps; step++) {
                event.register(ModelResourceLocation.standalone(family.model(step)));
            }
        }
    }

    /**
     * Wraps every composite block's baked models so they can draw overlays.
     *
     * <p>Done here, over the finished map, because that is the only place where <i>every</i> variant
     * exists: all forty stair rotations, the wall's assembled multipart models, each slab half. The
     * wrapper needs no knowledge of any of them — it copies whatever quads its wrapped model
     * produced — so one pass over the map covers a block family of any size.
     *
     * <p>Inventory models take a different wrapper. An item has no block entity and so no model data
     * to be handed; it resolves its overlays per stack instead. Same quads, same sprites, different
     * way in.
     */
    private static void wrapForOverlays(java.util.Map<ModelResourceLocation, BakedModel> models) {
        java.util.Set<ResourceLocation> composites = new java.util.HashSet<>();
        for (var block : net.minecraft.core.registries.BuiltInRegistries.BLOCK) {
            if (block instanceof com.tarosie.granularity.content.CompositeStone) {
                composites.add(net.minecraft.core.registries.BuiltInRegistries.BLOCK.getKey(block));
            }
        }

        ResourceLocation stonecutter = net.minecraft.core.registries.BuiltInRegistries.BLOCK
                .getKey(GranularityBlocks.STONECUTTER.get());
        int blocks = 0;
        int items = 0;
        int flat = 0;
        int finished = 0;
        int stopped = 0;
        for (var entry : models.entrySet()) {
            ModelResourceLocation key = entry.getKey();
            if (!composites.contains(key.id())) {
                continue;
            }
            if (key.variant().equals("inventory")) {
                // Flat item models are left alone. A `item/generated` sprite gives its layer tint
                // index 0 -- the very index that means "the block's surface" on a block model -- so
                // an overlay would faithfully retexture the whole 16x16 square and bury whatever the
                // item actually is. A lever is drawn that way, and came out an unreadable mossy
                // block. isGui3d() is exactly the question "is this model block-shaped".
                if (!entry.getValue().isGui3d()) {
                    flat++;
                    continue;
                }
                // The item's model is the block's model by parentage, so wrapping it the same way
                // makes the two draw identically -- which is the whole point: a worked block must not
                // look one way in the world and another in the hand.
                entry.setValue(new OverlayItemModel(entry.getValue()));
                items++;
            } else {
                // Finish first, overlays outside it: OverlayBakedModel passes the model data down, so
                // the finish decides which geometry is drawn and moss and dye are then applied to
                // whatever it chose. Moss grows on smooth stone as readily as on cobbled.
                // Every composite takes a finish now: a finish is a sprite on the base layer, and
                // the wrapper derives that from whatever shape it is handed.
                BakedModel wrapped = new OverlayBakedModel(new FinishBakedModel(entry.getValue()));
                if (key.id().equals(stonecutter)) {
                    // Outermost, so it sees the moss copies too and can leave them alone — it matches
                    // on the animated sprite rather than on a tint index. See StoppedBladeModel.
                    wrapped = new StoppedBladeModel(wrapped);
                    stopped++;
                }
                entry.setValue(wrapped);
                finished++;
                blocks++;
            }
        }
        Granularity.LOGGER.info(
                "Overlay-capable models: {} block variants and {} item models across {} composite "
                        + "blocks ({} flat item models left alone).", blocks, items, composites.size(), flat);
        // Said out loud because the failure is silent otherwise: if the smooth geometry never baked,
        // every smelted block would quietly render as cobbled and look merely like a wrong texture.
        Granularity.LOGGER.info("Finish-capable models: {} variants across {} finishes.",
                finished, com.tarosie.granularity.core.Finish.values().length);
        // Said out loud for the same reason the others are: a blade that goes on turning under moss is
        // a silent failure, and a count of zero here is the only warning you would get.
        Granularity.LOGGER.info("Stoppable blades: {} stonecutter variants can jam.", stopped);
    }


    public static void modifyBakingResult(ModelEvent.ModifyBakingResult event) {
        var models = event.getModels();
        wrapForOverlays(models);

        // A model whose JSON is absent is not returned as null -- ModelBakery substitutes its
        // missing-model placeholder, so a plain null check reports success while every layer
        // renders as the magenta-and-black cube. Comparing against the placeholder is what makes
        // a naming slip in the generator fail loudly instead of quietly.
        BakedModel missing = models.get(ModelBakery.MISSING_MODEL_VARIANT);

        BakedModel base = resolve(models, missing, BASE, "base layer");
        if (base == null) {
            return;
        }

        List<List<BakedModel>> families = new ArrayList<>(Family.values().length);
        for (Family family : Family.values()) {
            List<BakedModel> layers = new ArrayList<>(family.steps);
            for (int step = 1; step <= family.steps; step++) {
                BakedModel layer = resolve(models, missing, family.model(step),
                        family.name + " overlay " + step);
                if (layer == null) {
                    return;
                }
                layers.add(layer);
            }
            families.add(layers);
        }

        List<BakedModel> depthBases = new ArrayList<>(DEPTH_BANDS);
        for (int band = 0; band < DEPTH_BANDS; band++) {
            BakedModel ramp = resolve(models, missing, depthModel(band), "depth band " + band);
            if (ramp == null) {
                return;
            }
            depthBases.add(ramp);
        }

        // Two models from the same parts, differing only in whether they ramp with depth.
        //
        // World-generated stone ramps: the texture grades toward deepslate as you go down, because
        // that is a fact about where the rock formed. **A smelted block does not.** Ore blocks come
        // out of a furnace, so one built at bedrock and one built at sea level are the same object
        // and must look it — and they share this class only because they draw the same way.
        CompositionBakedModel composed = new CompositionBakedModel(base, families, depthBases);
        CompositionBakedModel unramped = new CompositionBakedModel(base, families);

        ResourceLocation blockId = ResourceLocation.fromNamespaceAndPath(Granularity.MODID, "natural_stone");
        models.put(new ModelResourceLocation(blockId, ""), composed);

        ResourceLocation oreId = ResourceLocation.fromNamespaceAndPath(Granularity.MODID, "ore_block");
        models.put(new ModelResourceLocation(oreId, ""), unramped);
        models.put(ModelResourceLocation.inventory(oreId), unramped);

        Granularity.LOGGER.info(
                "Natural stone model composed: 1 averaged base + {} overlay families x {} sprites, "
                        + "{} depth bands (world stone ramps; smelted ore block does not).",
                families.size(), families.get(0).size(), depthBases.size());
    }

    private static BakedModel resolve(java.util.Map<ModelResourceLocation, BakedModel> models,
                                      BakedModel missing, ResourceLocation id, String what) {
        BakedModel model = models.get(ModelResourceLocation.standalone(id));
        if (model == null || (missing != null && model == missing)) {
            Granularity.LOGGER.error(
                    "Granularity {} did not bake ({}). Run tools/extract_textures.py; "
                            + "natural stone will render untinted until it is present.", what, id);
            return null;
        }
        return model;
    }

    public static void registerBlockColours(RegisterColorHandlersEvent.Block event) {
        event.register(new CompositionBlockColour(), GranularityBlocks.NATURAL_STONE.get());
        event.register(new CompositeBlockColour(),
                GranularityBlocks.COBBLESTONE.get(), GranularityBlocks.GRAVEL.get(),
                GranularityBlocks.ALLOY_BLOCK.get(),
                GranularityBlocks.COBBLESTONE_SLAB.get(), GranularityBlocks.COBBLESTONE_STAIRS.get(),
                GranularityBlocks.COBBLESTONE_WALL.get(), GranularityBlocks.LEVER.get(),
                GranularityBlocks.FURNACE.get(), GranularityBlocks.DISPENSER.get(),
                GranularityBlocks.DROPPER.get(), GranularityBlocks.OBSERVER.get(),
                GranularityBlocks.PISTON.get(), GranularityBlocks.PISTON_HEAD.get(),
                GranularityBlocks.STONECUTTER.get());
        // The ore block renders like natural stone, so it takes natural stone's tints.
        event.register(new CompositionBlockColour(), GranularityBlocks.ORE_BLOCK.get());
    }

    /**
     * Drop items are greyscale sprites tinted by the colour they carry, so one item per class
     * covers all sixteen colours — the same economy §5 applies to blocks.
     */
    public static void registerItemColours(RegisterColorHandlersEvent.Item event) {
        // Every grain-backed item we register, tinted by which grain it is.
        for (var entry : GranularityItems.GRAIN_ITEMS.values()) {
            event.register(new GrainItemColour(), entry.get());
        }
        // One greyscale ingot sprite, coloured by which metal it is — the same trick the grain
        // items use, and the reason adding a metal costs no texture.
        for (var entry : GranularityItems.INGOT_ITEMS.entrySet()) {
            event.register(new MetalItemColour(), entry.getValue().get());
        }
        event.register(new CompositeItemColour(),
                GranularityItems.COBBLESTONE.get(), GranularityItems.GRAVEL.get(),
                GranularityItems.ORE_BLOCK.get(),
                GranularityItems.ALLOY_BLOCK.get(), GranularityItems.COBBLESTONE_SLAB.get(),
                GranularityItems.COBBLESTONE_STAIRS.get(), GranularityItems.COBBLESTONE_WALL.get(),
                GranularityItems.LEVER.get(), GranularityItems.FURNACE.get(),
                GranularityItems.DISPENSER.get(), GranularityItems.DROPPER.get(),
                GranularityItems.OBSERVER.get(), GranularityItems.PISTON.get(),
                GranularityItems.STONECUTTER.get());
    }

}
